import Navbar from "@/components/ui/Navbar";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { Suspense } from "react";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { UserLoading } from "@/components/ui/UserProfile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function LocaleLayout({ children, params }: Props) {
  // Ensure that the incoming `locale` is valid;
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const direction = locale === "ar" ? "rtl" : "ltr";

  return (
    <html dir={direction} lang={locale}>
      <body>
        <Suspense
          fallback={
            <div className="relative main-page-bg" dir="ltr">
              <nav
                className="w-full bg-neutral-200 sticky bg-linear-to-br from-green-50 flex justify-between items-center px-5
          to-black/10 border-b border-gray-500/30 top-0 left-0 h-16 animate-pulse"
              >
                <div className="text-gray-900">Logo</div>
                <div className="flex justify-center items-center">
                  <UserLoading />
                </div>
              </nav>

              <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2">
                <span className="flex items-center justify-center">
                  <svg
                    className="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                  >
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                    ></circle>
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                    ></path>
                  </svg>
                </span>
              </div>
            </div>
          }
        >
          <NextIntlClientProvider>
            <Navbar locale={locale} />
            <div className="main-page-bg">{children}</div>
            <Toaster />
          </NextIntlClientProvider>
        </Suspense>
      </body>
    </html>
  );
}
