import Navbar from "@/components/ui/Navbar";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { Suspense } from "react";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function LocaleLayout({ children, params }: Props) {
  // Ensure that the incoming `locale` is valid;
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const direction = locale === "ar" ? "rtl" : "ltr";

  return (
    <html dir={direction} lang={locale}>
      <body>
        <Suspense fallback={<div>loading...</div>}>
          <NextIntlClientProvider>
            <Navbar locale={locale} />
            <div className="main-page-bg">{children}</div>
            <Toaster />
          </NextIntlClientProvider>
        </Suspense>
      </body>
    </html>
  );
}
